version: '3.8'

services:

  mongo:
    image: mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rec
      MONGO_INITDB_ROOT_PASSWORD: rec
    ports:
      - 3002:27017
    volumes:
      - .bin/data:/data/db

  mongo-express:
    image: mongo-express
    restart: "no"
    ports:
      - 3001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rec
      ME_CONFIG_MONGODB_ADMINPASSWORD: rec
      ME_CONFIG_MONGODB_URL: mongodb://rec:rec@mongo:27017/
      ME_CONFIG_BASICAUTH: false
